# Generated by Django 4.1.1 on 2022-11-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
    ]
