# Generated by Django 4.1.1 on 2022-11-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='img',
            field=models.ImageField(default='default.png', upload_to='user_images', verbose_name='фото'),
        ),
    ]
