# Generated by Django 4.1.1 on 2022-11-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profil_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='img',
            field=models.ImageField(default=None, upload_to='user_images', verbose_name='фото'),
        ),
    ]
