# Generated by Django 4.1.1 on 2022-10-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новость'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
