# Generated by Django 4.1.1 on 2022-10-25 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_news_options_remove_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='avtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='aвтор'),
        ),
         migrations.AlterField(
            model_name='news',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,verbose_name='статия енгізу'),
        ),
    ]
