# Generated by Django 4.1.1 on 2022-10-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_news_avtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
    ]
