# Generated by Django 4.1.1 on 2022-10-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_statia_aty_remove_statia_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statia',
        ),
    ]
