# Generated by Django 4.1.1 on 2022-10-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statia',
            name='text',
        ),
        migrations.RemoveField(
            model_name='statia',
            name='title',
        ),
    ]
