# Generated by Django 4.1.1 on 2022-11-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_statia_views_alter_statia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statia',
            name='poto',
            field=models.ImageField(default='default.png', upload_to='news_images', verbose_name='фото'),
        ),
    ]
