# Generated by Django 4.1.1 on 2022-11-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_statia_poto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statia',
            name='poto',
            field=models.ImageField(default='natural.jpg', upload_to='news_images', verbose_name='фото'),
        ),
    ]
