# Generated by Django 4.2.2 on 2024-03-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_statia_poto'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_naz', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Файл атауы')),
                ('d_doc', models.FileField(upload_to='documents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='statia',
            name='poto',
            field=models.ImageField(default='default.png', upload_to='news_images', verbose_name='фото'),
        ),
    ]
